# Generated by Django 6.0.4 on 2026-04-09 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobpost',
            options={'verbose_name': 'Job Post', 'verbose_name_plural': 'Job Posts'},
        ),
    ]
