# Generated by Django 6.0.4 on 2026-04-29 14:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_jobpost_deadline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_jobs', to=settings.AUTH_USER_MODEL),
        ),
    ]
