# Generated by Django 6.0.4 on 2026-05-26 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_jobpost_is_vip_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpost',
            old_name='is_vip',
            new_name='is_featured',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
