# Generated by Django 6.0.4 on 2026-05-28 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_rename_is_vip_jobpost_is_featured_delete_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
