"""
Django settings for jobplatformapis project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import paypalrestsdk

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-dp^g#34!tcobai3wi5o-tm-ga3a7vq17r*pnzczz*c4a&on1$k'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

PAYPAL_CLIENT_ID = 'AdBrJ3TR3wSR8DLM8MKbCGoGURUj4CRNwQdGpBvfkR8AetQS9givn4nGjEFFuS-77nXJKDn9lMkQhP8e'
PAYPAL_SECRET = 'EO1SW-JXTxnO6_7VOgBOhIK1ZO_WYKYkT-OfBWG-5NtqX6fX2HBcx1UlnOo2WHD3rfo_hwS1QWLiZ3sm'

paypalrestsdk.configure({
  "mode": "sandbox", # Đổi thành "live" khi triển khai thật
  "client_id": PAYPAL_CLIENT_ID,
  "client_secret": PAYPAL_SECRET
})

PAYPAL_RETURN_URL = 'https://vicareer.app/payment-success'
PAYPAL_CANCEL_URL = 'https://vicareer.app/payment-cancel'

# Cấu hình MoMo Sandbox (Dùng chung cho Developer)
MOMO_PARTNER_CODE = "MOMOBKUN20180529"
MOMO_ACCESS_KEY = "klm05TvNBzhg7h7j"
MOMO_SECRET_KEY = "at67qH6mk8w5Y1nAyMoYKMWACiEi2bsa"
MOMO_ENDPOINT = "https://test-payment.momo.vn/v2/gateway/api/create"

MOMO_RETURN_URL = "https://vicareer.app/payment-success"
MOMO_IPN_URL = "https://vicareer.app/momo-ipn"

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'jobs.apps.JobsConfig',
    'users.apps.UsersConfig',
    'applications.apps.ApplicationsConfig',
    'ckeditor',
    'ckeditor_uploader',
    'django_filters',
    'cloudinary',
    'rest_framework',
    'oauth2_provider',
    'drf_yasg',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'jobplatformapis.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'jobplatformapis.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'jobplatformdb',
        'USER': 'root',
        'PASSWORD': 'Abc123',
        'HOST': 'localhost',
    }
}

AUTH_USER_MODEL = 'users.User'


import pymysql
pymysql.install_as_MySQLdb()
pymysql.version_info = (2, 2, 1, 'final', 0)


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
import os

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

CKEDITOR_UPLOAD_PATH = "jobs_desc/%Y/%m/"

# settings.py
import cloudinary
import cloudinary.uploader
import cloudinary.api
cloudinary.config(
  	cloud_name = "dokabu3ng",
  	api_key = "577294329223111",
  	api_secret = "FR262rDX7cNVj64RyjoKc-kdZx8"
)

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
        'rest_framework.authentication.SessionAuthentication',]
}